{% set name = "synthetic-data" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/synthetic-data-{{ version }}.tar.gz
  sha256: 7cf783aa40c11110edd11a6d76256ea368d20ceda8f7633707b5f69f6a5a8764

build:
  noarch: python
  #script_env:
  #  - PYTHONUTF8=1
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.21.0
    - scikit-learn >=1.0.2
    - scipy >=1.7.0
    - dataprofiler >=0.8.8

test:
  imports:
    - synthetic_data

about:
  home: https://github.com/capitalone/synthetic-data
  summary: Generates complex, nonlinear datasets for use with deep learning/black box models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
