{% set name = "synthetic-data" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/synthetic-data-{{ version }}.tar.gz
  sha256: c832d61c8fa3e57494ff4a627c1f4d0a5c6412fc1825da26a372d0d218e3ba81

build:
  noarch: python
  script_env:
    - PYTHONUTF8=1
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.21.0
    - scikit-learn >=1.1.2
    - scipy >=1.7.0
    - dataprofiler >=0.8.8

test:
  imports:
    - synthetic_data

about:
  home: https://github.com/capitalone/synthetic-data
  summary: Generates complex, nonlinear datasets for use with deep learning/black box models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
